services:
  postgres:
    image: postgres:16
    container_name: boardgamepicker-commercial-postgres

    environment:
      POSTGRES_DB: boardgamepicker_commercial
      POSTGRES_USER: boardgamepicker
      POSTGRES_PASSWORD: boardgamepicker_dev

    ports:
      - "5433:5432"

    volumes:
      - boardgamepicker_commercial_postgres_data:/var/lib/postgresql/data

volumes:
  boardgamepicker_commercial_postgres_data: