"""add play history index

Revision ID: 1cf21b3df911
Revises: 7c7a656f6774
Create Date: 2026-09-13 10:20:49.354231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf21b3df911'
down_revision: Union[str, Sequence[str], None] = '7c7a656f6774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
    "ix_plays_user_id_played_at",
    "plays",
    [
        "user_id",
        "played_at",
    ],
    unique=False,
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
    "ix_plays_user_id_played_at",
    table_name="plays",
)
    # ### end Alembic commands ###
