"""Add BGG username to users

Revision ID: 55fc55210cf3
Revises: f9c7d1c4c9eb
Create Date: 2026-09-05 07:02:45.168880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fc55210cf3'
down_revision: Union[str, Sequence[str], None] = 'f9c7d1c4c9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bgg_username', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'bgg_username')
    # ### end Alembic commands ###
