"""Add persistent players

Revision ID: fee9cd03fb47
Revises: 55fc55210cf3
Create Date: 2026-09-06 22:03:20.193559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee9cd03fb47'
down_revision: Union[str, Sequence[str], None] = '55fc55210cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_players_user_normalized_name')
    )
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    op.add_column('play_participants', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_play_participants_player_id'), 'play_participants', ['player_id'], unique=False)
    op.create_foreign_key(None, 'play_participants', 'players', ['player_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'play_participants', type_='foreignkey')
    op.drop_index(op.f('ix_play_participants_player_id'), table_name='play_participants')
    op.drop_column('play_participants', 'player_id')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
